### ISSUE TITLE
іменування

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-36-React-to-do-app#1]
https://github.com/BohdanLuts/home-work-lesson-36-React-to-do-app/blob/7518bf567627ede36816aed10b5f3cb775f9927c/src/components/forms/ToDoForm/index.jsx#L10
- краще назвати в однині, оскільки множина зазвичай використовується для масивів і при підтримці під таким іменем очікуєш бачити саме масив.

**Comment by BohdanLuts** [comment]
Виправлено!
