### ISSUE TITLE
артефакт

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-36-React-to-do-app#2]
https://github.com/BohdanLuts/home-work-lesson-36-React-to-do-app/blob/7518bf567627ede36816aed10b5f3cb775f9927c/src/components/ToDoList/index.jsx#L22
- залишився з вихідної реалізації. Тут пощастило, це не вплинуло, оскільки на початку має бути false, а по факту інше falsy-значення undefined, але в ішній ситуації могло впливати

**Comment by BohdanLuts** [comment]
Виправлено на isDone, так як isFavourite вже не використовувався
