### ISSUE TITLE
вкладеність стилів

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-36-React-to-do-app#3]
https://github.com/BohdanLuts/home-work-lesson-36-React-to-do-app/blob/7518bf567627ede36816aed10b5f3cb775f9927c/src/components/ToDoList/ToDoList.module.sass#L20
- вкладеності краще використовувати для медіа-запитів, псевдо-класів/елементів. Або там де якась явно стала стандартна структура. Найкраще буде по максимуму використовувати класи і по мінімуму вкладеність. Для самоперевірки можна, наприклад, себе запитати: "Чи використовував би я цю вкладеність в css?", типу
`.todosListItem .task, .todosListItem .done, .todosListItem .notDone {...}` (бо тут саме можливості SASS спонукають використовувати зайві кладення)
Або так: "Якщо я зміню верстку, чи доведеться мені лізти в стилі і вностити відповідні виправлення в селекторах?"

**Comment by BohdanLuts** [comment]
Допустив зайві табуляціі, була потреба у групуванні, а не у вкладенності.
Виправлено!

**Comment by pecourses** [comment]
Тут найбільша підстава в тому, що при переведенні курсора на новий рядок ентером курсор автоматично ставиться з відступом, тому дуже легко випадково прописати вкладеність...
